"""Add relationships

Revision ID: 2300e2500ef6
Revises: 5e82cb58382c
Create Date: 2025-06-07 14:33:16.554111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2300e2500ef6'
down_revision: Union[str, None] = '5e82cb58382c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'deterrence_permission', 'bird_detections', ['detection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deterrence_permission', type_='foreignkey')
    # ### end Alembic commands ###
