"""Delete unnecessary variables

Revision ID: 4daa60ac55ee
Revises: 2a88c5188ded
Create Date: 2025-06-06 15:49:52.218369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4daa60ac55ee'
down_revision: Union[str, None] = '2a88c5188ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deterrence_actions', 'triggered_by')
    op.drop_column('deterrence_actions', 'parameters')
    op.drop_column('deterrence_actions', 'device_type')
    op.drop_column('deterrence_actions', 'action')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deterrence_actions', sa.Column('action', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('deterrence_actions', sa.Column('device_type', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('deterrence_actions', sa.Column('parameters', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('deterrence_actions', sa.Column('triggered_by', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
