"""add user_id to DeterrenceAction

Revision ID: 7bab6f5aa500
Revises: 1c379c5600da
Create Date: 2025-06-05 16:43:52.079401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bab6f5aa500'
down_revision: Union[str, None] = '1c379c5600da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deterrence_actions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'deterrence_actions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deterrence_actions', type_='foreignkey')
    op.drop_column('deterrence_actions', 'user_id')
    # ### end Alembic commands ###
