"""add video_path column

Revision ID: d605d3d51012
Revises: 4daa60ac55ee
Create Date: 2025-06-06 16:52:33.971497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd605d3d51012'
down_revision: Union[str, None] = '4daa60ac55ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bird_detections', sa.Column('video_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bird_detections', 'video_path')
    # ### end Alembic commands ###
